# version: "3"
# services:
#   php-container:
#     image: php:7.1
#     ports:
#       - 8000:8000
#     tty: true
#     working_dir: /app
#     volumes:
#       - ./:/app

version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
